// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/DriveNormal.h"
#include "Commands/DriveStraight.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    driveJoy.reset(new Joystick(0));
    
    driveStraightButton.reset(new JoystickButton(driveJoy.get(), 1));
    driveStraightButton->WhileHeld(new DriveStraight());
    driveNormalButton.reset(new JoystickButton(driveJoy.get(), 1));
    driveNormalButton->WhileHeld(new DriveNormal());

    // SmartDashboard Buttons

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getDriveJoy() {
   return driveJoy;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

#if 0
float OI::GetDriveY() {
	return driveJoy->GetRawAxis(1);
}

float OI::GetDriveX() {
	return driveJoy->GetRawAxis(0);
}

float OI::GetTwistX() {
	return driveJoy->GetRawAxis(4);
}
float OI::GetThrot() {
	return driveJoy->GetRawAxis(2);
}
float OI::GetThrot2() {
	return driveJoy->GetRawAxis(3);
}
#endif
