// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<SpeedController> RobotMap::driveLeftTalon;
std::shared_ptr<SpeedController> RobotMap::driveRightTalon;
std::shared_ptr<RobotDrive> RobotMap::driveTankDrive;
std::shared_ptr<AnalogGyro> RobotMap::driveGyro;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    driveLeftTalon.reset(new Talon(0));
    lw->AddActuator("Drive", "LeftTalon", (Talon&) driveLeftTalon);
    
    driveRightTalon.reset(new Talon(1));
    lw->AddActuator("Drive", "RightTalon", (Talon&) driveRightTalon);
    
    driveTankDrive.reset(new RobotDrive(driveLeftTalon, driveRightTalon));
    
    driveTankDrive->SetSafetyEnabled(true);
        driveTankDrive->SetExpiration(0.1);
        driveTankDrive->SetSensitivity(0.5);
        driveTankDrive->SetMaxOutput(1.0);

    driveGyro.reset(new AnalogGyro(0));
    lw->AddSensor("Drive", "Gyro", driveGyro);
    driveGyro->SetSensitivity(0.007);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
